### ISSUE TITLE
Pie chart error on same values

### ISSUE THREAD

**Issue by mpalencia** [ghalex/vue3-charts#24] opened 2022-01-19 02:33 UTC
Hi mate, got a bug on piechat if any of the values are the same 

This works:

export const plByMonth = [
  { name: 'Jan', pl: 1000, avg: 500, inc: 300 },
  { name: 'Feb', pl: 2000, avg: 900, inc: 400 },
  { name: 'Apr', pl: 400, avg: 400, inc: 500 },
  { name: 'Mar', pl: 3100, avg: 1300, inc: 700 },
  { name: 'May', pl: 200, avg: 100, inc: 200 },
  { name: 'Jun', pl: 600, avg: 400, inc: 300 },
  { name: 'Jul', pl: 500, avg: 90, inc: 100 }
]

This will not work

export const plByMonth = [
  { name: 'Jan', pl: 1000, avg: 500, inc: 300 },
  { name: 'Feb', pl: 1000, avg: 900, inc: 400 },
  { name: 'Apr', pl: 1000, avg: 400, inc: 500 },
  { name: 'Mar', pl: 1000, avg: 1300, inc: 700 },
  { name: 'May', pl: 200, avg: 100, inc: 200 },
  { name: 'Jun', pl: 600, avg: 400, inc: 300 },
  { name: 'Jul', pl: 500, avg: 90, inc: 100 }
]

Im referring here on the 'pl'

**Comment by ghalex** [comment] 2022-02-01 08:17
Duplicate of #23

**Closed by ghalex** 2022-02-01 08:17 UTC
